using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace TruckerApp.UserForm
{
    public partial class FrmCasheList : Form
    {
        public FrmCasheList()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            TruckerApp.TruckersEntities dbContext = new TruckerApp.TruckersEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Cashes.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    cashesBindingSource.DataSource = dbContext.Cashes.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
