//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressBook
    {
        public int ID { get; set; }
        public string Fname { get; set; }
        public string LName { get; set; }
        public string Mobile { get; set; }
        public string Mobile2 { get; set; }
        public string Phone { get; set; }
        public string Addres { get; set; }
        public string postalCode { get; set; }
        public string Jobs { get; set; }
        public string Description { get; set; }
        public Nullable<int> DriverID_FK { get; set; }
    }
}
