//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccNum
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string BankName { get; set; }
        public string AccNumber { get; set; }
        public string AccCart { get; set; }
        public string AccISBN { get; set; }
        public string Editor { get; set; }
    }
}
