//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public int CashID { get; set; }
        public Nullable<int> QueueID_FK { get; set; }
        public Nullable<int> Pos { get; set; }
        public Nullable<int> CashDesk { get; set; }
        public Nullable<byte> userID { get; set; }
    
        public virtual Queue Queue { get; set; }
        public virtual User User { get; set; }
    }
}
